### ISSUE TITLE
Fights service when deployed to k8s doesn't get random fighters

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#284]
When deploying to k8s currently the fights service is not resolving random fighters from the heroes & villains services. This has something to do with Stork. Not sure yet if its just on OpenShift or all Kubernetes flavors.

Currently investigating the issue with @cescoffier and @aureamunoz , but wanted to create this ticket here for tracking purposes.

**Comment by cescoffier** [comment]
Since https://github.com/quarkusio/quarkus/commit/b89fece02881a35354482900fc2db255d42adb8a#diff-f15233cea0f87118b4441038738a41197a55fb6e3e1f3e06efd1dc4b41fe0143R160, the Kubernetes _services_ created by Quarkus now contain two ports:

- HTTP (8080)
- HTTPS (8443)

The problem with the two ports is that our application exposes a single one, so the second one will constantly fail. 

When Stork lists the endpoint ports, it finds the two ports and does not know which one to use. So, it picks the first one, which has 50% of selecting the wrong one. 

@Sgitario added a feature to Stork that allows selecting the port. However, having a new, almost mandatory attribute for something that should not be is inconvenient. But that's a workaround until we can improve the generation.

\CC @Sgitario @iocanel

**Comment by cescoffier** [comment]
With https://github.com/quarkusio/quarkus/pull/33237, you would need to set `port-name: http` for the clients using stork.

**Comment by cescoffier** [comment]
Did you try with the latest stork Kubernetes service discovery. I released
it a few hours ago.

**Comment by Sgitario** [comment]
I tried https://github.com/quarkusio/quarkus/pull/33237 with https://github.com/quarkusio/quarkus/issues/33131 and the new property works fine: https://github.com/quarkusio/quarkus/issues/33131#issuecomment-1541375678

**Comment by edeandrea** [comment]
I haven't tried it yet. How would I do that? Build Quarkus main and then build super heroes off of that?

**Comment by cescoffier** [comment]
@edeandrea no need for the full quarkus. Just use Stork 2.2.0 (set the dependency version on the kubernetes service discovery dependency). 

The PR bumping the Stork version in Quarkus has been opened. I hope it will be merged and include for the next release (cut today if I'm not mistaken).

**Comment by cescoffier** [comment]
The _fix_ has been integrated in the latest Quarkus release:
https://github.com/quarkusio/quarkus/releases/tag/3.0.3.Final
