### ISSUE TITLE
What about having Quinoa for the Angular app?

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-super-heroes#87]
With the announcement of Quinoa, I was wondering if we could use it for the Angular app

https://quarkus.io/blog/quinoa-modern-ui-with-no-hassle/

**Comment by edeandrea** [comment]
I'm certainly not tied to angular. The only drawback I can see is that currently we only have a single container image for the ui. Doing this means we'd have to have 4, like we do for the other services (Java 11, Java 17, native Java 11, native Java 17).

**Comment by edeandrea** [comment]
@agoncal After learning a little bit more about Quinoa, it doesn't seem like its a replacement for the Angular - just a way to bring the Angular (or whatever SPA framework you're using) into Quarkus and provide a nice dev experience with it.

That being said, would it make sense to "wrap" the Angular UI in a Quarkus Quinoa app? A downside to that would be that we'd now have to maintain 8 container images (Java 11, Java 17, native Java 11, native Java 17, all for both amd64 & arm64 platforms).

I'm almost thinking that if we wanted to use Quinoa that we merge the Angular UI into the `rest-fights` app. WDYT?

**Comment by agoncal** [comment]
I actually watched the Quarkus insight on Quinoa (https://www.youtube.com/watch?v=ya8To5V1QUU) and also thought of merging the UI into the Fight microservice (and this way avoid 4 extra containers)

**Comment by edeandrea** [comment]
Would there be any downsides? The only one I can see is that we wouldn't be able to separate the UI as static content anymore. I'm not sure how important that might be.

Can you think of anything else? @cescoffier WDYT?

**Comment by agoncal** [comment]
@cescoffier Quinoa will not help unfortunatelly (we will still need to use the entire Node environment). In terms of development it makes life easier (Quqrkus runs on one port, Node on another one), but it's true that we can't have the UI deployed in a CDN, for example.

I'm in 2 minds: maybe deploying the UI to a CDN makes more sense as it is a real life use case

**Comment by edeandrea** [comment]
@cescoffier Are you building the UI in the workshops? Or just running it? If you're just running it, why not just `docker run -it quay.io/quarkus-super-heroes/ui-super-heroes:latest`? That would bring up the UI and assume that the `rest-fights` service is running on http://localhost:8082.

**Comment by agoncal** [comment]
We are not building it. It is already bundled and ready to use. There is also a Docker file to build it (inspired by what you did in the Super Heroes ;o)

https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/super-heroes/ui-super-heroes/src/main/docker/Dockerfile.build-native

**Comment by edeandrea** [comment]
Ahhh I see - the workshop still has the UI bundled inside a Quarkus app, whereas the superheroes separated the UI into its own thing.

**Comment by edeandrea** [comment]
@agoncal / @cescoffier did we come to a decision on this? I'll summarize from above comments:

## Pros
- Quinoa is new & cool
- No more Node.js tooling required
- Being able to have tests that test the UIs to know if something broke
- Main UI would now be part of the `rest-fights` app, so we'd eliminate maintenance of 2 container images (Node.js amd64 & arm64)

## Cons
- Not able to deploy the angular app as static content anymore

Feel free to add anything I may have missed.

**Comment by agoncal** [comment]
I'm still in two minds, but I think that being able to deploy the Angular app as static content is important. At the end of the day, that's what real projects do.

So I'll leave it like it is.

The question could be: does it make sense to introduce Quinoa to an Angular project (without Quarkus)?

**Comment by edeandrea** [comment]
@cescoffier / @agoncal coming back to this a few months later - are we all still feeling that things are better left as-is? If so, I will close out this issue.

**Comment by agoncal** [comment]
I have lost track of what Quinoa is up to today. For the knowledge I had back then on Quinoa, it does not make sense in our sample. You can close the issue

**Comment by ia3andy** [comment]
I just found this repo while looking into best practices to make micro-services with Quarkus. I've asked Eric on why you didn't use Quinoa for the UI then ended up in this discussion.

So here are facts which could help you change your decision because I don't really get why you ended up closing this (beside the fact that changing requires work):
- Quinoa is not tied to any UI framework
- You can use Quinoa to ease dev/build (and integration with Maven) but serve the output as static content (using NGinx or whatever)
- The webui built static content is in `target/quinoa-build` after the maven build (and can be used by a dockerfile)
- Quinoa can be disabled only for the runtime (keep the build)
- Quinoa can now install NodeJs/NPM so only Maven is needed for dev/build
- The best use-case for Quinoa is when there is a Quarkus API Gateway because you can integrate the UI directly with the Quarkus backend
- I am working on a blog article to explain the different deployment options with Quinoa:
  - Quarkus only (backend + frontend) - default
  - Quarkus backend + Quarkus frontend (separate images for scaling)
  - Quarkus backend + NGinx (or other) frontend

**Comment by edeandrea** [comment]
@agoncal / @cescoffier let me know if you'd like to revisit this conversation with @ia3andy. Some of the things he mentioned I wasn't aware of, so maybe it would impact what we do.

I think that, if we can keep the current deployment strategy (building/pushing Node.js images), yet enhance the developer inner loop, plus show off another cool Quarkus feature, then that would be a win.

**Comment by edeandrea** [comment]
@ia3andy 

This point you made

> The webui built static content is in `target/quinoa-build` after the maven build (and can be used by a dockerfile)

Is the `target/quinoa-build` the static source or the produced output from the maven build (`mvn package`)? If we decided to use Quinoa, how would we run a `prod` build to generate the `prod` sources?

For example, our current `Dockerfile` does this:

```dockerfile
# First stage builds the application
FROM registry.access.redhat.com/ubi8/nodejs-16:1 as builder

# Add dependencies
COPY --chown=1001:1001 package*.json $HOME/

# Install dependencies
RUN npm install

# Add application sources
COPY --chown=1001:1001 . $HOME/

# Run build
RUN npm run build && \
    npm prune --production

# Second stage copies the application to the minimal image
FROM registry.access.redhat.com/ubi8/nodejs-16-minimal:1

# ENV variables
# API_BASE_URL: URL of service to connect to
# HTTP_PORT: The http port this service listens on
ENV HTTP_PORT=8080 \
    NODE_ENV=production

# Copy the application source and build artifacts from the builder image to this one
COPY --chown=1001:1001 --from=builder $HOME $HOME

# Expose the http port
EXPOSE $HTTP_PORT

# Run script uses standard ways to run the application
CMD npm start
```

Notice where it does `npm run build && npm prune --production` in the builder stage. Would we be able to accomplish the same thing using Quinoa?

**Comment by holly-cummins** [comment]
I'm -1 for running Quinoa for local dev and node.js in prod. I think that would be a *lot* of work, and we might end up with the worst of both worlds - very complex instructions, having to maintain node.js images, and a lot of moving parts. 

However, I'm +1 for a move to Quinoa. It would nicely simplify the instructions for running locally - just `cd` to the UI project and `quarkus dev`. It also allows us to showcase all the nice things Quinoa does, and the suitability of Quarkus for modern web apps. 

No matter what language we go for, we need some kind of server to serve the web app files. At the moment we're using express on node. js. Since I'm on a team that builds Java web servers, I like the idea of using a Java web server, and showing how Quarkus can be small and light and fast for these kinds of applications. 

If we wanted to reduce the combinatorics of maintaining all the images, instead of supporting Java 11, 17, and native, on arm64 and amd64, we could just do native. That should be a nice alternative to express.js.

**Comment by holly-cummins** [comment]
I've just done the PR for moving the super-heroes workshop to Quinoa, if we want to see what the changes look like there: https://github.com/quarkusio/quarkus-workshops/pull/230

Looking at the two codebases, I think the changes would be similar for this sample. In both cases, there was a node app (running on express) which served the `API_BASE_URL` configuration and static files, and we would swap that for a Java server which served similar config, but with the goodness of integration to Quarkus config. 

I don't totally follow the discussion about static files being different between the two codebases. With Quinoa, we'd just build the production artifacts and images using the provided docker file, including for native. So I don't think there's a problem for prod, but maybe I'm missing a subtlety.

**Comment by edeandrea** [comment]
For me this then raises the question: should we re-write the UI using something more modern (like React)? I thought I saw something internally where someone had done that already.

It would be nice to have a test suite for the UI so that we can turn on dependabot. There are also a few enhancements for the UI, but as it stands today, I don't really dare touch it with a 10 foot pole.

**Comment by holly-cummins** [comment]
I think we can keep those two concerns separate. I'm a big +1 for UI tests, dependabot, and React (or an alternative like Lit ... or anything but Angular, really). But it's orthogonal to switching the backend for the UI (which is what introducing Quarkus + Quinoa would be doing). I've raised https://github.com/quarkusio/quarkus-super-heroes/issues/290 for discussion of the javascript libraries.
